/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Chris' at '19/03/16 14:23' with Gradle 2.4
 *
 * @author Chris, @date 19/03/16 14:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
